# Generated by Django 5.0.6 on 2024-10-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='order_date',
        ),
    ]
