# Generated by Django 5.0.6 on 2024-10-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orderdeletionrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDeletionRequest',
        ),
    ]
