# Generated by Django 5.0.6 on 2024-10-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_orderdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
