# Generated by Django 5.0.6 on 2024-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortedproducts',
            name='backlight',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='certification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='cooling_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='dpi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='form_factor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='mouse_pad_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='noise_cancellation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='power_wattage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='ram_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='ram_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='sensor_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='socket_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='storage_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='storage_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='switch_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedproducts',
            name='video_memory',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
