# Generated by Django 5.0.6 on 2024-11-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_sortedproducts_noise_cancellation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortedproducts',
            name='resolution',
        ),
    ]
